version: '2.2'

services:
  elasticsearch:
    build:
      dockerfile: elasticsearch-with-plugins
      context: .
    image: training-es:7.9.3
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - path.repo=/usr/share/elasticsearch/backup
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - backup:/usr/share/elasticsearch/backup
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: training-es:7.9.3
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - path.repo=/usr/share/elasticsearch/backup
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - backup:/usr/share/elasticsearch/backup
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana
    networks:
      - esnet
    ports: ['5601:5601']

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  backup:
    driver: local

networks:
  esnet: